### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Charlie-robin** [sachie5/portfolio#2]
# Feedback

## Requirements:

1. A deployed website (using GitHub Pages): DONE
2. A public GitHub repository for your codebase: DONE
3. Use HTML & SCSS: DONE
4. Make good use of semantic HTML elements: DONE
5. Be responsive (mobile-first) and built with accessibility in mind: DONE
6. Code is highly readable (good naming and indented correctly): DONE

## Score

[MARKING-SCHEME](https://github.com/nology-tech/Verde-Course-Resources/blob/main/student-resources/01-web/marking-scheme.md)

| Category             | Score    |
| -------------------- | -------- |
| Site Output          | 40 / 50  |
| Responsiveness       | 15 / 15  |
| Code Knowledge & Use | 15 / 20  |
| Readability          | 10 / 15  |
| Version Control      | 10 / 10  |
| Total Score          | 90 / 110 |

### Positive

- Your project is good! it has been a great exercise for you to build a website from a wireframe.

- Your BEM is spot on, with the right level of nesting and easy to understand blocks of styles.

- You are using a lot of semantic tags, keep this up.

- You demonstrate a solid understanding of the majority of topics we have covered so far, keep it up and keep on using BEM, SCSS, grid and flex.

- Nice work applying feedback from the demo `grid-template-columns: repeat(5%, 9);`

- As you progress through the course keep coming back and updating the profile information and projects section :).

### Constructive

- Try to get into the habit of completing a README.md, as we move forward these are going to be the best places to talk about your project and show off features and code without someone having to clone down your project.

  - You can include screen shots and example code snippets.
  - Here is an example from a previous \_nologist called [Luke](https://github.com/luke-welbourn/personal-portfolio)

- I think it would be a good idea to have a go at introducing some folders to your project. This will add more structure to it and make your life easier when you come back to update projects and the intro section.

  - With the example below all of the images and icons have been put into a `assets` folder. The styles from the `main.scss` have been broken up into multiple scss files and are in the `styles` folder.

```txt
portfolio/
│
├── index.html
│
├── assets/
│   ├── BEM.svg
│   └── OTHER IMAGES ETC...
│
├── styles/
│   ├── main.scss
│   ├── main.css
│   ├── _profile.scss
│   ├── _variables.scss
│   └── OTHER SCSS FILES ETC...
│
└── README.md
```

- You can start to break apart your styles from your `_profile.scss`.
  - Having specific files related to each part of your project makes it easier to maintain as the project grows.
  - Below I have taken the `.intro` styles and moved them into their own `_intro.scss` file.

```scss
// _intro.scss
@use "./variables" as *;

.intro {
  height: 516px;
  padding: 20px;

  &__greeting {
    font-size: 16px;
    padding: 30px 0;
  }

  &__image {
    width: 20px;
    padding-right: 5px;
    // GREAT USE OF A MODIFIER BTW :)
    &--large {
      display: none;
    }
  }

  &__statement {
    font-size: 48px;
  }
}

// MEDIA QUERY FOR THE SPECIFIC STYLES OF THE FILE

@media screen and (min-width: 768px) {
  .intro {
    display: flex;
    justify-content: space-around;
    padding: 80px 0;

    &__words {
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: flex-end;
      padding-left: 40px;
    }

    &__image {
      &--large {
        display: flex;
        align-items: center;
      }
    }
  }
}
```

```scss
@use "./variables" as *;

// BRING ALL YOUR STYLE FILES INTO YOUR main.scss
@use "./intro";
@use "./about";
@use "./projects";
@use "./footer";

* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  width: 100%;
}

body {
  font-family: $font-body;
  background-color: $background-color;
  color: $secondary-color;
}
```

- Any questions feel free to reach out.

---
